title: tellsiddh's blog
description: A simple blog powered by Jekyll
url: "https://blog.tellsiddh.com"
baseurl: ""

permalink: /:categories/:title/

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "dark" # or "default", "air", "neon" etc.
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

author: siddarth

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

twitter_username: tellsiddh
github_username: tellsiddh

defaults:
  -
    scope:
      path: ""           #   ‚Üê applies to all files in the site
    values:
      head_includes: |
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1292884866168336"
                 crossorigin="anonymous"></script>
