title: tellsiddh's Blog
description: A simple blog powered by Jekyll
url: "https://blog.tellsiddh.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "dark" # or "default", "air", "neon" etc.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

author: siddarth

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
